blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('createblog/', views.create_blog, name='create'),
    path('<slug>/', views.blog_detail, name='detail'),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userAccount.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userAccount/urls.py
from django.urls import path
from . import views

app_name = 'userAccount'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blogs(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg', blank=True, upload_to='images')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def des_snippet(self):
        return self.description[:30] + '....See more'

userAccount/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Blogs

class CreateBlog(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = ['title', 'slug', 'description', 'image']

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Blogs
from . import forms


def blog_list(request):
    queryset = Blogs.objects.all().order_by('date')
    context = {
        'blogList': queryset
    }
    return render(request, 'blog/bloglist.html', context)

@login_required(login_url='userAccount:login')
def create_blog(request):
    if request.method == 'POST':
        form = forms.CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            messages.success(request, 'Successfully, you have created new blog.....')
            return redirect('blog:list')
    else:
        form = forms.CreateBlog()

    context = {
        'form': form
    }
    return render(request, 'blog/createblog.html', context)

def blog_detail(request, slug):
    queryset = Blogs.objects.get(slug = slug)
    context = {
        'blog': queryset
    }
    return render(request, 'blog/blogdetail.html', context)

userAccount/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages

def home(request):
    return render(request, 'userAccount/home.html')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulation, you have been Successfully registered.....')
            #user = form.save()
            #login(request, user)
            return redirect('userAccount:login')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }
    return render(request, 'userAccount/signup.html', context)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:list')
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }
    return render(request, 'userAccount/login.html', context)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'Successfully, you have been logged out.....')
        return redirect('userAccount:login')

blog/templates/blog/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel = "icon" type = "image/jpg" href = "{% static 'blog.jpg' %}">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Blog | Tech Revolution</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarTogglerDemo01"
          aria-controls="navbarTogglerDemo01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'blog:list' %}">Tech REVOLUTION</a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <!-- <li class="nav-item active">
              <a class="nav-link" href="#"
                >Home</a>
            </li> -->
          </ul>
          <h6 style="color:white;"> Welcome, <i> <u>  {{ user.username}} </u> </i> to Tech Revolution. </h6>
          <a class="nav-item nav-link" href="{% url 'blog:create' %}"><button class="btn btn-success" type="submit">
            Create Blog
          </button></a>
              {% if user.is_authenticated %}
              <form
                class="form-inline my-2 my-lg-0"
                action="{% url 'userAccount:logout' %}"
                method="POST"
              >
                {% csrf_token %}
                <a class="nav-item nav-link"><button class="btn btn-danger" type="submit">
                  LOGOUT
                </button></a>
              </form>
              {% endif %}
            </div>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <footer>
        <div class="row justify-content-center">
            <div class="col-md-5 text-center">
                <h4 class="heading">SAHEB GHOSH</h4>
                <div class="heading-underline"></div>
		<strong>Contact Info</strong>
		<p>sahebghosh310@gmail.com</p>
		<a href="https://de.linkedin.com/in/saheb-ghosh-547842159" target="_blank"><i class="fab fa-linkedin"></i></a>
		<a href="https://www.xing.com/profile/Saheb_Ghosh" target="_blank"><i class="fab fa-xing-square"></i></a>
		<a href="https://github.com/sahebghosh" target="_blank"><i class="fab fa-github-square"></i></a>

            </div>
            <hr class="socket">
	        @copy; Saheb Ghosh.

        </div>
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
  </body>
</html>

blog/templates/blog/blogdetail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container mt-4">

<div class="card text-center">
  <div class="card-header">
  <h2>BLOG DETAILS</h2>  
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ blog.title }}</h5>
    <p class="card-text">{{ blog.description }}</p>
    <a href="{% url 'blog:list' %}" class="btn btn-primary">Back to Blog</a>
  </div>
  <div class="card-footer">
<small class="text-muted">Posted on {{ blog.date }}</small>
</div>
</div>

</div>

{% endblock %}

blog/templates/blog/bloglist.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="d-flex justify-content-center mt-2">
{% if messages %}
<ul class="messages" style="color:green;">
    {% for message in messages %}
    <h5{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </h5>
    {% endfor %}
</ul>
{% endif %}
</div>

<div class="container mt-4">
  <div class="row">
      {% for blog in blogList %}
    <div class="col-lg-4 mb-2">  
      <div class="card" style="height:493px;">
          <img class="card-img-top" src="{{ blog.image.url }}" alt="Author Image" width="70px" height="250px"/>
            <div class="card-body">
              <h5 class="card-title">{{ blog.title }}</h5>
              <p class="card-text">{{ blog.des_snippet }}</p>
              <a href="{% url 'blog:detail' slug=blog.slug %}" class="btn btn-outline-primary btn-sm">Read More</a>
              <a href="#" class="btn btn-outline-danger"><i class="far fa-heart"></i></a>
            </div>
            <div class="card-footer">
              <small class="text-muted">Created by {{ blog.author }}</small>
            </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/blog/createblog.html
{% extends 'blog/base.html' %} {% block content %} {% load crispy_forms_tags %}
<div class="d-flex justify-content-center mt-2">
  <h3>Create new Blog</h3>
</div>
<div class="container mt-4">
  <form
    action="{% url 'blog:create' %}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <div class="form-group">
      {{ form | crispy }}
    </div>

    <input type="submit" value="Create" class="btn btn-success" />
    <a href="{% url 'blog:list' %}" class="btn btn-primary">Back to Blog</a>
  </form>
</div>
{% endblock %}

userAccount/templates/userAccount/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel = "icon" type = "image/jpg" href = "{% static 'blog.jpg' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>Blog | Tech Revolution</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarTogglerDemo01"
          aria-controls="navbarTogglerDemo01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'userAccount:home' %}">Tech REVOLUTION</a>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <footer>
        <div class="row justify-content-center">
            <div class="col-md-5 text-center">
                <h4 class="heading">SAHEB GHOSH</h4>
                <div class="heading-underline"></div>
    <strong>Contact Info</strong>
    <p>sahebghosh310@gmail.com</p>
    <a href="https://de.linkedin.com/in/saheb-ghosh-547842159" target="_blank"><i class="fab fa-linkedin"></i></a>
    <a href="https://www.xing.com/profile/Saheb_Ghosh" target="_blank"><i class="fab fa-xing-square"></i></a>
    <a href="https://github.com/sahebghosh" target="_blank"><i class="fab fa-github-square"></i></a>

            </div>
            <hr class="socket">
          @copy; Saheb Ghosh.

        </div>
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
  </body>
</html>

userAccount/templates/userAccount/home.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel = "icon" type = "image/jpg" href = "{% static 'blog.jpg' %}">
    <link rel = "stylesheet" type = "text/css" href = "{% static 'main.css' %}">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Blog | Tech Revolution</title>
    <style>
      body {
        background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.9)), url({% static 'blog.jpg' %}) center/cover fixed no-repeat;
        color: white;
        text-align: center;
        padding-top: 230px;
      }
      hr {
        border-color: white;
        width: 30%;
        height: 2px;
      }
      .hello {
        padding-left: 40px;
        font-size: 25px;
      }
    </style>
  </head>
  <body class="hello">
    <h1>WELCOME TO TECH REVOLUTION</h1>
    <hr />
    <div>
      <a href="{% url 'userAccount:login' %}"><button type="button" class="btn btn-outline-success btn-lg">Signin</button></a>   or
      <a href="{% url 'userAccount:signup' %}"><button type="button" class="btn btn-outline-success btn-lg">Sign Up</button></a>
    </div>
  </body>
</html>

userAccount/templates/userAccount/login.html
{% extends 'userAccount/base.html' %} {% block content %} {% load crispy_forms_tags %}
<div class="d-flex justify-content-center mt-2">
{% if messages %}
<ul class="messages" style="color:green;">
    {% for message in messages %}
    <h6{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </h6>
    {% endfor %}
</ul>
{% endif %}
</div>
<div class="d-flex justify-content-center mt-2">
  <h3>Signin</h3>
</div>
<div class="d-flex justify-content-center mt-2">
    <form action="{% url 'userAccount:login' %}" method="POST">
      {% csrf_token %}
      {{ form | crispy }}
      {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}" />
      {% endif %}
      <button type="submit" class="btn btn-primary">Signin</button>
      <a href="{% url 'userAccount:home' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock %}

userAccount/templates/userAccount/signup.html
{% extends 'userAccount/base.html' %} {% block content %} {% load crispy_forms_tags %}
<div class="d-flex justify-content-center mt-2">
  <h3>Register</h3>
</div>
<div class="d-flex box justify-content-center mt-2">
  <form class="site-form" action="{% url 'userAccount:signup' %}" method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
      <a href="{% url 'userAccount:home' %}" class="btn btn-danger">Cancel</a>
  </form>
</div>

{% endblock %}